kind: pipeline
type: docker
name: Azure Static WebApp

steps:
- name: Build and upload static web app
  environment:
    APITOKEN:
     from_secret: APITOKEN
    HUGO_VERSION: 0.97.1
  image: mcr.microsoft.com/appsvc/staticappsclient:stable
  commands:
  - /bin/staticsites/StaticSitesClient --apiToken $APITOKEN --outputLocation "staticfiles" --app "/drone/src/staticfiles" --deploymentaction "upload" --appBuildCommand "echo 1"
